// +build !ignore_autogenerated

/*
 * licensed to vmware.
 */

// This file was autogenerated by defaulter-gen. Do not edit it manually!

package kuber

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	return nil
}
