apiVersion: apps/v1
kind: Deployment
metadata:
  name: purser-controller
  labels:
    app: purser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purser
  template:
    metadata:
      labels:
        app: purser
    spec:
      containers:
      - name: purser-controller
        image: gurusreekanth/controller-amd64:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080