# base image
FROM node:9.6.1

LABEL maintainer="VMware <hkatyal@vmware.com>"

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json package-lock.json ./

RUN npm install
RUN npm install -g @angular/cli@6.2.1

# add app
COPY . .

# start app
CMD ng serve --host 0.0.0.0