apiVersion: v1
kind: ServiceAccount
metadata:
  name: purser-service-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: purser-permissions
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "watch", "list", "update", "create", "delete"]
  - apiGroups: ["vmware.purser.com"]
    resources: ["groups", "subscribers"]
    verbs: ["get", "watch", "list", "update", "create", "delete"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["*"]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: purser-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: purser-permissions
subjects:
  - kind: ServiceAccount
    name: purser-service-account
    namespace: default
---
# This is the service that should be used by the clients of Dgraph to talk to the server.
apiVersion: v1
kind: Service
metadata:
  name: purser-db
  labels:
    app: purser
spec:
  type: LoadBalancer
  ports:
  - port: 5080
    targetPort: 5080
    name: zero-grpc
  - port: 6080
    targetPort: 6080
    name: zero-http
  - port: 8080
    targetPort: 8080
    name: server-http
  - port: 9080
    targetPort: 9080
    name: server-grpc
  - port: 8000
    targetPort: 8000
    name: ratel-http
  - port: 3030
    targetPort: 3030
    name: purser
  selector:
    app: purser
---
# This StatefulSet runs 1 pod with one Zero, one Server & one Ratel containers.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: purser-dgraph
spec:
  serviceName: "dgraph"
  replicas: 1
  selector:
      matchLabels:
        app: purser
  template:
    metadata:
      labels:
        app: purser
    spec:
      containers:
      - name: ratel
        image: dgraph/dgraph:v1.0.9
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 10Mi
            cpu: 100m
          requests:
            memory: 10Mi
            cpu: 100m
        ports:
        - containerPort: 8000
          name: ratel-http
        command:
          - dgraph-ratel
      - name: zero
        image: dgraph/dgraph:v1.0.9
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1000Mi
            cpu: 300m
          requests:
            memory: 1000Mi
            cpu: 300m
        ports:
        - containerPort: 5080
          name: zero-grpc
        - containerPort: 6080
          name: zero-http
        volumeMounts:
        - name: datadir
          mountPath: /dgraph
        command:
          - bash
          - "-c"
          - |
            set -ex
            dgraph zero --my=$(hostname -f):5080
      - name: server
        image: dgraph/dgraph:v1.0.9
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1000Mi
            cpu: 300m
          requests:
            memory: 1000Mi
            cpu: 300m
        ports:
        - containerPort: 8080
          name: server-http
        - containerPort: 9080
          name: server-grpc
        volumeMounts:
        - name: datadir
          mountPath: /dgraph
        command:
          - bash
          - "-c"
          - |
            set -ex
            dgraph server --my=$(hostname -f):7080 --lru_mb 2048 --zero purser-dgraph-0.dgraph.default.svc.cluster.local:5080
      terminationGracePeriodSeconds: 60
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purser-controller
spec:
  selector:
    matchLabels:
        app: purser
  replicas: 1
  template:
    metadata:
      labels:
        app: purser
    spec:
      serviceAccountName: purser-service-account
      containers:
      - name: purser-controller
        image: kreddyj/controller-amd64:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: 1000Mi
            cpu: 300m
          requests:
            memory: 1000Mi
            cpu: 300m
        ports:
        - containerPort: 3030
          name: purser
