apiVersion: v1
kind: Service
metadata:
  name: purser-ui
  labels:
    run: purser-ui
    app: purser
spec:
  type: NodePort
  ports:
  - port: 4200
    protocol: TCP
  selector:
    run: purser-ui
    app: purser
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purser-ui
spec:
  selector:
    matchLabels:
      run: purser-ui
      app: purser
  replicas: 1
  template:
    metadata:
      labels:
        run: purser-ui
        app: purser
    spec:
      containers:
      - name: purser-ui
        image: vmwareh/purser-ui:latest
        ports:
        - containerPort: 4200
