# Service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: purser-service-account
---
# RBAC
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: purser-permissions
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "watch", "list", "update", "create", "delete"]
  - apiGroups: ["vmware.purser.com"]
    resources: ["groups", "subscribers"]
    verbs: ["get", "watch", "list", "update", "create", "delete"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
# Uncomment next three lines to enable interactions feature.
#  - apiGroups: ["*"]
#    resources: ["pods/exec"]
#    verbs: ["create"]
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: purser-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: purser-permissions
subjects:
  - kind: ServiceAccount
    name: purser-service-account
    namespace: default
---
# Service Purser - ports required for controller and ui
apiVersion: v1
kind: Service
metadata:
  name: purser
  labels:
    app: purser
spec:
  type: NodePort
  ports:
  - port: 3030
    targetPort: 3030
    nodePort: 30300
    protocol: TCP
    name: purser
  - port: 4200
    targetPort: 4200
    nodePort: 30303
    protocol: TCP
    name: purser-ui
  selector:
    app: purser
---
# Purser deployment - Replicas 1, Containers 2 (controller and UI)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purser
spec:
  selector:
    matchLabels:
        app: purser
  replicas: 1
  template:
    metadata:
      labels:
        app: purser
    spec:
      serviceAccountName: purser-service-account
      containers:
      - name: purser-controller
        image: kreddyj/controller-amd64:1.0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: 1000Mi
            cpu: 300m
          requests:
            memory: 1000Mi
            cpu: 300m
        ports:
        - containerPort: 3030
          name: purser
        command: ["/controller"]
        args: ["--log=info", "--interactions=disable", "--dgraphURL=purser-db", "--dgraphPort=9080"]
      - name: purser-ui
        image: kreddyj/purser-ui:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 4200