apiVersion: v1
kind: Service
metadata:
  name: purser-ui
  labels:
    run: purser-ui
    app: purser
spec:
  selector:
    app: purser
    run: purser-ui
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 4200
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purser-ui
spec:
  selector:
    matchLabels:
      app: purser
      run: purser-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: purser
        run: purser-ui
    spec:
      containers:
      - name: purser-ui
        image: kreddyj/purser-ui:1.0.2
        imagePullPolicy: Always
        resources:
          limits:
            memory: 1200Mi
            cpu: 500m
          requests:
            memory: 1200Mi
            cpu: 500m
        ports:
        - containerPort: 4200