/*
 * licensed to vmware.
 */

// This file was automatically generated by informer-gen

package internalversion

import (
	internalinterfaces "apiserver-builder/pkg/client/informers_generated/internalversion/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// MyKinds returns a MyKindInformer.
	MyKinds() MyKindInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// MyKinds returns a MyKindInformer.
func (v *version) MyKinds() MyKindInformer {
	return &myKindInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
