# Service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: purser-service-account
---
# RBAC
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: purser-permissions
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "watch", "list", "update", "create", "delete"]
  - apiGroups: ["vmware.purser.com"]
    resources: ["groups", "subscribers"]
    verbs: ["get", "watch", "list", "update", "create", "delete"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
# Uncomment next three lines to enable interactions feature.
#  - apiGroups: ["*"]
#    resources: ["pods/exec"]
#    verbs: ["create"]
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: purser-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: purser-permissions
subjects:
  - kind: ServiceAccount
    name: purser-service-account
    namespace: purser
---
apiVersion: v1
kind: Service
metadata:
  name: purser
spec:
  selector:
    app: purser
  ports:
  - protocol: TCP
    port: 3030
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purser
spec:
  selector:
    matchLabels:
        app: purser
  replicas: 1
  template:
    metadata:
      labels:
        app: purser
    spec:
      serviceAccountName: purser-service-account
      containers:
        - name: purser-controller
          image: kreddyj/controller-amd64:1.0.2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3030
          command: ["/controller"]
          args: ["--log=info", "--interactions=disable", "--dgraphURL=purser-db", "--dgraphPort=9080"]