/*
 * licensed to vmware.
 */

// This file was automatically generated by lister-gen

package internalversion

// MyKindListerExpansion allows custom methods to be added to
// MyKindLister.
type MyKindListerExpansion interface{}

// MyKindNamespaceListerExpansion allows custom methods to be added to
// MyKindNamespaceLister.
type MyKindNamespaceListerExpansion interface{}
